version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automated"
    commit-message:
      prefix: "chore"
      include: "scope"
    # Group updates to reduce PR noise
    groups:
      babel:
        patterns:
          - "@babel/*"
      eslint:
        patterns:
          - "eslint*"
      jest:
        patterns:
          - "jest*"
      webpack:
        patterns:
          - "webpack*"
          - "*-loader"
    
  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore"
