name: Build Validation

on:
  push:
    branches: [ main, CodeMirrorWork ]
  pull_request:
    branches: [ main ]

jobs:
  validate-build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 22.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install
      
    - name: Install ExTwee for format validation
      run: npm install -g extwee

    - name: Run quick validation
      run: npm run quick
      
    - name: Build and package story format
      run: npm run package
      
    - name: Validate format.js exists and is functional
      run: |
        if [ ! -f "dist/format.js" ]; then
          echo "❌ dist/format.js was not created"
          exit 1
        fi
        echo "✅ dist/format.js created successfully"
        
    - name: Test ExTwee compilation with format
      run: |
        cat > test-compile.twee << 'EOF'
        :: StoryTitle
        Test Story

        :: StoryData
        {
            "ifid": "12345678-ABCD-1234-ABCD-123456789ABC"
        }

        :: Start
        Hello, world!
        EOF
        
        extwee -s dist/format.js -i test-compile.twee -c -o test-output.html
        
        if [ ! -f "test-output.html" ]; then
          echo "❌ ExTwee compilation failed"
          exit 1
        fi
        
        echo "✅ ExTwee compilation successful"
        rm test-compile.twee test-output.html
        
    - name: Validate webpack bundle size
      run: |
        BUNDLE_SIZE=$(stat -c%s "build/format.bundle.js" 2>/dev/null || stat -f%z "build/format.bundle.js")
        echo "Bundle size: $BUNDLE_SIZE bytes"
        
        # Warn if bundle is larger than 1MB (1048576 bytes)  
        if [ "$BUNDLE_SIZE" -gt 1048576 ]; then
          echo "⚠️  Warning: Bundle size is larger than 1MB"
        else
          echo "✅ Bundle size is acceptable"
        fi