name: Update Dependencies

on:
  schedule:
    # Run weekly on Mondays at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/1.X'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
    - name: Install dependencies
      run: npm ci
      
    - name: Update dependencies
      id: update
      run: |
        # Check for updates
        if npm outdated > /dev/null 2>&1; then
          echo "No updates available"
          echo "has_updates=false" >> $GITHUB_OUTPUT
        else
          echo "Updates available"
          echo "has_updates=true" >> $GITHUB_OUTPUT
          
          # Update patch and minor versions only (safer)
          npm update
          
          # Check if package-lock.json changed
          if git diff --quiet package-lock.json; then
            echo "has_updates=false" >> $GITHUB_OUTPUT
          else
            echo "has_updates=true" >> $GITHUB_OUTPUT
          fi
        fi
        
    - name: Run tests after update
      if: steps.update.outputs.has_updates == 'true'
      run: |
        npm test
        npm run lint
        npm run build
        
    - name: Create Pull Request
      if: steps.update.outputs.has_updates == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'chore: update dependencies'
        title: 'chore: automated dependency updates'
        body: |
          ## Automated Dependency Updates
          
          This PR contains automated updates to package dependencies.
          
          ### Changes
          - Updated npm dependencies to latest patch/minor versions
          - All tests pass ✅
          - Build successful ✅
          - Linting passes ✅
          
          ### Review Notes
          - This only includes patch and minor version updates (safer)
          - Major version updates require manual review
          - Please review the changelog of updated packages
          
          Generated by GitHub Actions 🤖
        branch: automated-dependency-updates
        delete-branch: true
        labels: |
          dependencies
          automated
          1.X