name: Setup Build Linking

# Manual workflow to setup the build linking system
on:
  workflow_dispatch:
    inputs:
      force_reset:
        description: 'Force reset existing worktrees'
        required: false
        default: false
        type: boolean

jobs:
  setup-builds:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout gh-pages branch
      uses: actions/checkout@v4
      with:
        ref: gh-pages
        fetch-depth: 0  # Fetch all history for all branches
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Git
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
    
    - name: Run setup script
      run: |
        if [ "${{ inputs.force_reset }}" == "true" ]; then
          echo "Force reset requested - cleaning up existing worktrees..."
          # Clean up any existing worktrees
          git worktree list | grep -v "$(pwd)" | awk '{print $1}' | xargs -r git worktree remove --force || true
        fi
        
        echo "Running setup script..."
        ./setup-builds.sh
    
    - name: Commit initial setup
      run: |
        if [ -n "$(git status --porcelain)" ]; then
          git add builds/ .github/
          git commit -m "🔧 Setup build file linking system
          
          - Created symbolic links to worktree dist folders
          - builds/1.X/ → ../worktrees/1.X/dist/
          - builds/2.X/ → ../worktrees/2.X/dist/  
          - builds/3.X/ → ../worktrees/main/dist/
          
          Generated by GitHub Actions on $(date -u)"
          git push origin gh-pages
          echo "Setup complete and committed!"
        else
          echo "No changes to commit - setup already complete"
        fi
    
    - name: Create summary
      run: |
        echo "## Build Linking Setup Complete" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Worktrees created for all branches**" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Symbolic links established**" >> $GITHUB_STEP_SUMMARY
        echo "✅ **Build files ready for serving**" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "**Directory structure:**" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "builds/" >> $GITHUB_STEP_SUMMARY
        echo "├── 1.X/ → ../worktrees/1.X/dist/" >> $GITHUB_STEP_SUMMARY
        echo "├── 2.X/ → ../worktrees/2.X/dist/" >> $GITHUB_STEP_SUMMARY
        echo "└── 3.X/ → ../worktrees/main/dist/" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "The automatic update workflow will now run daily to keep builds synchronized."